# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('emailAddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
