# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='firstName',
            new_name='first_name',
        ),
    ]
