# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170627_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='lastName',
            new_name='last_Name',
        ),
    ]
